/**
 * Seed catalog of Indian places.
 *
 * This is demo content served by the `places` provider adapter. In production
 * this adapter is replaced by a verified external provider (Google Places /
 * OSM / a curated CMS) — the business services never change.
 *
 * `dataTrust`: "verified" data comes from a trustworthy source; anything
 * "estimate" is AI/editorial and is clearly labelled in the UI.
 */
export const PLACE_CATEGORIES = [
  'temple',
  'gurudwara',
  'historical',
  'nature',
  'food',
  'shopping',
  'adventure',
  'family',
  'spiritual',
  'hidden-gem',
];

export const places = [
  {
    id: 'plc_taj_mahal',
    slug: 'taj-mahal',
    name: 'Taj Mahal',
    city: 'Agra',
    state: 'Uttar Pradesh',
    category: 'historical',
    categories: ['historical', 'family', 'spiritual'],
    description:
      'One of the Seven Wonders of the World and the crown of Mughal architecture. Best experienced at sunrise when the marble glows.',
    rating: 4.9,
    ratingCount: 128400,
    entryFee: 50,
    visitDurationMin: 180,
    bestTime: 'Sunrise (06:00–08:00)',
    openTime: '06:00',
    closeTime: '18:30',
    coordinates: { lat: 27.1751, lng: 78.0421 },
    imageSlug: 'agra-taj',
    popular: true,
    dataTrust: 'verified',
    tags: ['UNESCO', 'Monument', 'Sunrise'],
  },
  {
    id: 'plc_agra_fort',
    slug: 'agra-fort',
    name: 'Agra Fort',
    city: 'Agra',
    state: 'Uttar Pradesh',
    category: 'historical',
    categories: ['historical', 'family'],
    description: 'A red-sandstone Mughal fortress with a direct view of the Taj Mahal across the Yamuna.',
    rating: 4.7,
    ratingCount: 52100,
    entryFee: 50,
    visitDurationMin: 120,
    bestTime: 'Morning',
    openTime: '06:00',
    closeTime: '18:00',
    coordinates: { lat: 27.1795, lng: 78.0211 },
    imageSlug: 'agra-fort',
    popular: true,
    dataTrust: 'verified',
    tags: ['UNESCO', 'Fort', 'Viewpoint'],
  },
  {
    id: 'plc_mehtab_bagh',
    slug: 'mehtab-bagh',
    name: 'Mehtab Bagh',
    city: 'Agra',
    state: 'Uttar Pradesh',
    category: 'nature',
    categories: ['nature', 'family', 'hidden-gem'],
    description: 'A riverside garden with the most beautiful sunset view of the Taj Mahal, far from the crowds.',
    rating: 4.5,
    ratingCount: 21400,
    entryFee: 30,
    visitDurationMin: 60,
    bestTime: 'Sunset',
    openTime: '06:00',
    closeTime: '18:30',
    coordinates: { lat: 27.1797, lng: 78.04 },
    imageSlug: 'agra-taj',
    popular: false,
    dataTrust: 'verified',
    tags: ['Garden', 'Sunset'],
  },
  {
    id: 'plc_fatehpur_sikri',
    slug: 'fatehpur-sikri',
    name: 'Fatehpur Sikri',
    city: 'Agra',
    state: 'Uttar Pradesh',
    category: 'historical',
    categories: ['historical', 'spiritual'],
    description: 'The abandoned Mughal capital — Buland Darwaza and the tomb of Salim Chishti.',
    rating: 4.6,
    ratingCount: 19800,
    entryFee: 50,
    visitDurationMin: 150,
    bestTime: 'Morning',
    openTime: '06:00',
    closeTime: '18:00',
    coordinates: { lat: 27.0945, lng: 77.6679 },
    imageSlug: 'agra-fort',
    popular: false,
    dataTrust: 'verified',
    tags: ['UNESCO', 'Fort', 'Half-day'],
  },
  {
    id: 'plc_hawa_mahal',
    slug: 'hawa-mahal',
    name: 'Hawa Mahal',
    city: 'Jaipur',
    state: 'Rajasthan',
    category: 'historical',
    categories: ['historical', 'family'],
    description: 'The iconic pink "Palace of Winds" with 953 honeycomb windows built for royal women to watch street life.',
    rating: 4.5,
    ratingCount: 61200,
    entryFee: 50,
    visitDurationMin: 60,
    bestTime: 'Early morning',
    openTime: '09:00',
    closeTime: '16:30',
    coordinates: { lat: 26.9239, lng: 75.8267 },
    imageSlug: 'jaipur',
    popular: true,
    dataTrust: 'verified',
    tags: ['Landmark', 'Pink City'],
  },
  {
    id: 'plc_amber_fort',
    slug: 'amber-fort',
    name: 'Amber Fort',
    city: 'Jaipur',
    state: 'Rajasthan',
    category: 'historical',
    categories: ['historical', 'adventure', 'family'],
    description: 'A hilltop fort of marble and sandstone, reached by jeep or a short hike. Sheesh Mahal is the highlight.',
    rating: 4.7,
    ratingCount: 88400,
    entryFee: 100,
    visitDurationMin: 150,
    bestTime: 'Morning',
    openTime: '08:00',
    closeTime: '17:30',
    coordinates: { lat: 26.9855, lng: 75.8513 },
    imageSlug: 'jaipur',
    popular: true,
    dataTrust: 'verified',
    tags: ['UNESCO', 'Fort', 'Hike'],
  },
  {
    id: 'plc_city_palace_jaipur',
    slug: 'city-palace-jaipur',
    name: 'City Palace',
    city: 'Jaipur',
    state: 'Rajasthan',
    category: 'historical',
    categories: ['historical', 'family', 'shopping'],
    description: 'A living royal palace complex with museums, courtyards and the famous peacock gate.',
    rating: 4.6,
    ratingCount: 44300,
    entryFee: 200,
    visitDurationMin: 120,
    bestTime: 'Afternoon',
    openTime: '09:30',
    closeTime: '17:00',
    coordinates: { lat: 26.9256, lng: 75.8235 },
    imageSlug: 'jaipur',
    popular: true,
    dataTrust: 'verified',
    tags: ['Palace', 'Museum'],
  },
  {
    id: 'plc_india_gate',
    slug: 'india-gate',
    name: 'India Gate',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'historical',
    categories: ['historical', 'family', 'nature'],
    description: 'A war memorial arch on the Rajpath lawns — best visited in the evening when it is lit up.',
    rating: 4.6,
    ratingCount: 91200,
    entryFee: 0,
    visitDurationMin: 45,
    bestTime: 'Evening',
    openTime: '00:00',
    closeTime: '23:59',
    coordinates: { lat: 28.6129, lng: 77.2295 },
    imageSlug: 'delhi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Monument', 'Free', 'Evening'],
  },
  {
    id: 'plc_red_fort',
    slug: 'red-fort',
    name: 'Red Fort',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'historical',
    categories: ['historical', 'family'],
    description: 'Delhi’s grand Mughal fort and the site of India’s Independence Day address.',
    rating: 4.5,
    ratingCount: 60400,
    entryFee: 50,
    visitDurationMin: 120,
    bestTime: 'Morning',
    openTime: '09:30',
    closeTime: '16:30',
    coordinates: { lat: 28.6562, lng: 77.241 },
    imageSlug: 'delhi',
    popular: true,
    dataTrust: 'verified',
    tags: ['UNESCO', 'Fort'],
  },
  {
    id: 'plc_qutub_minar',
    slug: 'qutub-minar',
    name: 'Qutub Minar',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'historical',
    categories: ['historical', 'family'],
    description: 'A 73-metre victory tower surrounded by the ruins of India’s first mosque.',
    rating: 4.6,
    ratingCount: 47800,
    entryFee: 40,
    visitDurationMin: 90,
    bestTime: 'Morning',
    openTime: '07:00',
    closeTime: '17:00',
    coordinates: { lat: 28.5245, lng: 77.1855 },
    imageSlug: 'delhi',
    popular: true,
    dataTrust: 'verified',
    tags: ['UNESCO', 'Tower'],
  },
  {
    id: 'plc_lotus_temple',
    slug: 'lotus-temple',
    name: 'Lotus Temple',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'temple',
    categories: ['temple', 'spiritual', 'family'],
    description: 'A Bahá’í House of Worship shaped like a lotus flower, open to people of all faiths.',
    rating: 4.7,
    ratingCount: 39800,
    entryFee: 0,
    visitDurationMin: 60,
    bestTime: 'Morning',
    openTime: '09:00',
    closeTime: '17:00',
    coordinates: { lat: 28.5535, lng: 77.2588 },
    imageSlug: 'delhi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Temple', 'Free', 'Architecture'],
  },
  {
    id: 'plc_akshardham',
    slug: 'akshardham-temple',
    name: 'Akshardham Temple',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'temple',
    categories: ['temple', 'spiritual', 'family'],
    description: 'A vast modern temple complex with intricate carvings, exhibitions and an evening water show.',
    rating: 4.8,
    ratingCount: 62300,
    entryFee: 0,
    visitDurationMin: 150,
    bestTime: 'Late afternoon',
    openTime: '10:00',
    closeTime: '20:00',
    coordinates: { lat: 28.6127, lng: 77.2773 },
    imageSlug: 'delhi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Temple', 'Family'],
  },
  {
    id: 'plc_bangla_sahib',
    slug: 'bangla-sahib',
    name: 'Gurudwara Bangla Sahib',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'gurudwara',
    categories: ['gurudwara', 'spiritual'],
    description: 'One of Delhi’s most prominent gurudwaras, known for its golden dome, sarovar and community kitchen.',
    rating: 4.8,
    ratingCount: 54100,
    entryFee: 0,
    visitDurationMin: 60,
    bestTime: 'Morning',
    openTime: '00:00',
    closeTime: '23:59',
    coordinates: { lat: 28.6265, lng: 77.2088 },
    imageSlug: 'amritsar',
    popular: true,
    dataTrust: 'verified',
    tags: ['Gurudwara', 'Free', 'Langar'],
  },
  {
    id: 'plc_chandni_chowk',
    slug: 'chandni-chowk',
    name: 'Chandni Chowk',
    city: 'Old Delhi',
    state: 'Delhi',
    category: 'food',
    categories: ['food', 'shopping', 'hidden-gem'],
    description: 'Old Delhi’s legendary bazaar — paranthe wali gali, jalebis, and lanes packed with street food.',
    rating: 4.4,
    ratingCount: 70200,
    entryFee: 0,
    visitDurationMin: 120,
    bestTime: 'Morning (for food)',
    openTime: '10:00',
    closeTime: '20:00',
    coordinates: { lat: 28.6507, lng: 77.2303 },
    imageSlug: 'delhi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Street food', 'Market'],
  },
  {
    id: 'plc_connaught_place',
    slug: 'connaught-place',
    name: 'Connaught Place',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'shopping',
    categories: ['shopping', 'food', 'family'],
    description: 'Delhi’s white Georgian shopping circle with cafés, bookstores and restaurants.',
    rating: 4.5,
    ratingCount: 58800,
    entryFee: 0,
    visitDurationMin: 90,
    bestTime: 'Evening',
    openTime: '10:00',
    closeTime: '23:00',
    coordinates: { lat: 28.6315, lng: 77.2167 },
    imageSlug: 'delhi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Shopping', 'Cafés'],
  },
  {
    id: 'plc_golden_temple',
    slug: 'golden-temple',
    name: 'Golden Temple (Harmandir Sahib)',
    city: 'Amritsar',
    state: 'Punjab',
    category: 'gurudwara',
    categories: ['gurudwara', 'spiritual', 'family'],
    description: 'The holiest shrine of Sikhism, gleaming gold at the centre of the Amrit Sarovar.',
    rating: 4.9,
    ratingCount: 118000,
    entryFee: 0,
    visitDurationMin: 120,
    bestTime: 'Early morning / night',
    openTime: '00:00',
    closeTime: '23:59',
    coordinates: { lat: 31.62, lng: 74.8765 },
    imageSlug: 'amritsar',
    popular: true,
    dataTrust: 'verified',
    tags: ['Gurudwara', 'Free', 'Spiritual'],
  },
  {
    id: 'plc_kashi_vishwanath',
    slug: 'kashi-vishwanath',
    name: 'Kashi Vishwanath Temple',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'temple',
    categories: ['temple', 'spiritual'],
    description: 'One of the twelve Jyotirlingas of Shiva, at the heart of Varanasi’s sacred old city.',
    rating: 4.8,
    ratingCount: 46300,
    entryFee: 0,
    visitDurationMin: 90,
    bestTime: 'Early morning',
    openTime: '04:00',
    closeTime: '23:00',
    coordinates: { lat: 25.3109, lng: 83.0107 },
    imageSlug: 'varanasi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Temple', 'Shiva', 'Spiritual'],
  },
  {
    id: 'plc_dashashwamedh_ghat',
    slug: 'dashashwamedh-ghat',
    name: 'Dashashwamedh Ghat',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'spiritual',
    categories: ['spiritual', 'family', 'food'],
    description: 'Varanasi’s main ghat, home of the Ganga Aarti each evening — a bucket-list experience.',
    rating: 4.7,
    ratingCount: 39100,
    entryFee: 0,
    visitDurationMin: 90,
    bestTime: 'Sunset (Ganga Aarti)',
    openTime: '00:00',
    closeTime: '23:59',
    coordinates: { lat: 25.3065, lng: 83.0105 },
    imageSlug: 'varanasi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Ghat', 'Aarti', 'River'],
  },
  {
    id: 'plc_sarnath',
    slug: 'sarnath',
    name: 'Sarnath',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'historical',
    categories: ['historical', 'spiritual', 'family'],
    description: 'Where Buddha gave his first sermon — the Dhamek Stupa and a superb archaeological museum.',
    rating: 4.6,
    ratingCount: 15200,
    entryFee: 25,
    visitDurationMin: 120,
    bestTime: 'Morning',
    openTime: '06:00',
    closeTime: '18:00',
    coordinates: { lat: 25.3762, lng: 83.021 },
    imageSlug: 'varanasi',
    popular: false,
    dataTrust: 'verified',
    tags: ['Buddhist', 'Museum'],
  },
  {
    id: 'plc_hampi',
    slug: 'hampi',
    name: 'Hampi Ruins',
    city: 'Hampi',
    state: 'Karnataka',
    category: 'historical',
    categories: ['historical', 'adventure', 'hidden-gem'],
    description: 'A surreal boulder-strewn landscape filled with Vijayanagara temples and ruins.',
    rating: 4.8,
    ratingCount: 37200,
    entryFee: 40,
    visitDurationMin: 300,
    bestTime: 'Early morning',
    openTime: '06:00',
    closeTime: '18:00',
    coordinates: { lat: 15.335, lng: 76.46 },
    imageSlug: 'jaipur',
    popular: true,
    dataTrust: 'verified',
    tags: ['UNESCO', 'Ruins', 'Backpacker'],
  },
  {
    id: 'plc_mysore_palace',
    slug: 'mysore-palace',
    name: 'Mysore Palace',
    city: 'Mysuru',
    state: 'Karnataka',
    category: 'historical',
    categories: ['historical', 'family'],
    description: 'The dazzling Indo-Saracenic palace of the Wodeyars, lit by 100,000 bulbs on Sundays.',
    rating: 4.7,
    ratingCount: 58100,
    entryFee: 100,
    visitDurationMin: 120,
    bestTime: 'Evening (illumination)',
    openTime: '10:00',
    closeTime: '17:30',
    coordinates: { lat: 12.3051, lng: 76.6551 },
    imageSlug: 'jaipur',
    popular: true,
    dataTrust: 'verified',
    tags: ['Palace', 'Illumination'],
  },
  {
    id: 'plc_gateway_india',
    slug: 'gateway-of-india',
    name: 'Gateway of India',
    city: 'Mumbai',
    state: 'Maharashtra',
    category: 'historical',
    categories: ['historical', 'family', 'nature'],
    description: 'Mumbai’s waterfront arch, built for a royal visit — the start of ferry rides to Elephanta.',
    rating: 4.5,
    ratingCount: 81200,
    entryFee: 0,
    visitDurationMin: 45,
    bestTime: 'Sunset',
    openTime: '00:00',
    closeTime: '23:59',
    coordinates: { lat: 18.922, lng: 72.8347 },
    imageSlug: 'delhi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Landmark', 'Sea'],
  },
  {
    id: 'plc_marine_drive',
    slug: 'marine-drive',
    name: 'Marine Drive',
    city: 'Mumbai',
    state: 'Maharashtra',
    category: 'nature',
    categories: ['nature', 'family'],
    description: 'Mumbai’s famous "Queen’s Necklace" promenade along the Arabian Sea.',
    rating: 4.6,
    ratingCount: 44700,
    entryFee: 0,
    visitDurationMin: 60,
    bestTime: 'Sunset',
    openTime: '00:00',
    closeTime: '23:59',
    coordinates: { lat: 18.9432, lng: 72.8234 },
    imageSlug: 'varanasi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Sea', 'Sunset'],
  },
  {
    id: 'plc_johri_bazaar',
    slug: 'johri-bazaar',
    name: 'Johri Bazaar',
    city: 'Jaipur',
    state: 'Rajasthan',
    category: 'shopping',
    categories: ['shopping', 'food', 'hidden-gem'],
    description: 'Jaipur’s old jewellery and textile market — the place for lac bangles and block prints.',
    rating: 4.3,
    ratingCount: 9800,
    entryFee: 0,
    visitDurationMin: 90,
    bestTime: 'Evening',
    openTime: '10:00',
    closeTime: '21:00',
    coordinates: { lat: 26.921, lng: 75.825 },
    imageSlug: 'jaipur',
    popular: false,
    dataTrust: 'verified',
    tags: ['Shopping', 'Textiles'],
  },
  {
    id: 'plc_rishikesh',
    slug: 'rishikesh',
    name: 'Rishikesh & Ganga',
    city: 'Rishikesh',
    state: 'Uttarakhand',
    category: 'adventure',
    categories: ['adventure', 'nature', 'spiritual'],
    description: 'The yoga capital of the world with river rafting, suspension bridges and Ganga aarti.',
    rating: 4.7,
    ratingCount: 42600,
    entryFee: 0,
    visitDurationMin: 240,
    bestTime: 'Morning',
    openTime: '00:00',
    closeTime: '23:59',
    coordinates: { lat: 30.0869, lng: 78.2676 },
    imageSlug: 'varanasi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Adventure', 'Yoga', 'River'],
  },
  {
    id: 'plc_dal_lake',
    slug: 'dal-lake',
    name: 'Dal Lake',
    city: 'Srinagar',
    state: 'Jammu & Kashmir',
    category: 'nature',
    categories: ['nature', 'family', 'hidden-gem'],
    description: 'Srinagar’s mirror-like lake with houseboats and shikara rides against the Zabarwan hills.',
    rating: 4.8,
    ratingCount: 35800,
    entryFee: 0,
    visitDurationMin: 180,
    bestTime: 'Morning',
    openTime: '06:00',
    closeTime: '20:00',
    coordinates: { lat: 34.1107, lng: 74.8691 },
    imageSlug: 'varanasi',
    popular: true,
    dataTrust: 'verified',
    tags: ['Lake', 'Shikara', 'Scenic'],
  },
];

export const placesById = new Map(places.map((p) => [p.id, p]));
export const placesBySlug = new Map(places.map((p) => [p.slug, p]));
