export const ROUTES = {
  home: '/',
  explore: '/explore',
  dashboard: '/dashboard',
  plan: '/plan',
  trips: '/trips',
  trip: (id) => `/trips/${id}`,
  liveTrip: (id) => `/trips/${id}/live`,
  budget: (id) => `/trips/${id}/budget`,
  transport: '/transport',
  hotels: '/hotels',
  nearby: '/nearby',
  assistant: '/assistant',
  favorites: '/favorites',
  profile: '/profile',
  settings: '/settings',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
};
