export const ROUTES = {
  home: '/',
  explore: '/explore',
  about: '/about',
  features: '/features',
  login: '/login',
  register: '/register',
  forgot: '/forgot-password',
  reset: '/reset-password',
  plan: '/plan',
  dashboard: '/dashboard',
  trips: '/trips',
  trip: (id) => `/trips/${id}`,
  live: (id) => `/trips/${id}/live`,
  budget: (id) => `/trips/${id}/budget`,
  editTrip: (id) => `/trips/${id}/edit`,
  transport: '/transport',
  hotels: '/hotels',
  places: '/places',
  nearby: '/nearby',
  assistant: '/assistant',
  favorites: '/favorites',
  profile: '/profile',
  settings: '/settings',
};
