import bcrypt from 'bcryptjs';

/**
 * Demo seed data — a demo account plus one fully-planned AI trip so the
 * product is instantly explorable. Clearly AI-generated content is labelled.
 */
export async function buildSeed() {
  const passwordHash = await bcrypt.hash('Demo@1234', 10);
  const nowIso = new Date().toISOString();

  const user = {
    id: 'usr_demo',
    name: 'Naveen',
    email: 'demo@yatragenie.ai',
    passwordHash,
    googleId: null,
    avatar: '',
    role: 'user',
    isEmailVerified: true,
    preferences: {
      travelStyle: 'comfort',
      budgetPreference: 5000,
      transport: 'train',
      stay: 'medium',
      interests: ['historical', 'temple', 'food'],
      travelFrequency: 'monthly',
    },
    createdAt: nowIso,
    updatedAt: nowIso,
    lastLoginAt: null,
  };

  const trip = {
    id: 'trp_demo_agra',
    userId: user.id,
    title: 'Delhi → Agra Weekend',
    origin: 'Delhi',
    destination: 'Agra',
    startDate: '2026-08-22',
    endDate: '2026-08-23',
    travelers: { adults: 2, children: 0 },
    budget: 5000,
    travelStyle: 'comfort',
    transportPreference: 'train',
    stayPreference: 'medium',
    interests: ['historical', 'temple', 'food'],
    status: 'planned',
    overview:
      'A classic 2-day golden-triangle escape: the Taj Mahal at sunrise, Agra Fort, Mehtab Bagh at sunset, Fatehpur Sikri and Old Delhi street food.',
    budgetBreakdown: {
      transport: 1200,
      hotel: 1800,
      food: 900,
      activities: 600,
      other: 500,
    },
    itinerary: [
      {
        id: 'day_1',
        day: 1,
        title: 'Taj & the Mughal trail',
        summary: 'Arrive by Shatabdi, see the Taj at its best, then Agra Fort and a sunset garden.',
        items: [
          {
            id: 'itm_1_1',
            time: '06:00',
            endTime: '08:00',
            place: 'Shatabdi Express to Agra',
            category: 'transport',
            duration: '2h 00m',
            distance: '—',
            transport: 'train',
            cost: 590,
            priority: 'high',
            notes: 'NDLS → AGC. Departure is an estimate — verify on IRCTC.',
            coordinates: null,
            imageSlug: 'delhi',
          },
          {
            id: 'itm_1_2',
            time: '08:15',
            endTime: '09:00',
            place: 'Breakfast near Tajganj',
            category: 'food',
            duration: '45m',
            distance: '2.0 km',
            transport: 'auto',
            cost: 200,
            priority: 'medium',
            notes: 'Bedmi puri & jalebi are a local favourite.',
            coordinates: null,
            imageSlug: 'delhi',
          },
          {
            id: 'itm_1_3',
            time: '09:00',
            endTime: '12:00',
            place: 'Taj Mahal',
            category: 'historical',
            duration: '3h 00m',
            distance: '—',
            transport: 'walk',
            cost: 50,
            priority: 'high',
            notes: 'Buy tickets online in advance. East gate is quieter.',
            coordinates: { lat: 27.1751, lng: 78.0421 },
            imageSlug: 'agra-taj',
          },
          {
            id: 'itm_1_4',
            time: '12:30',
            endTime: '13:30',
            place: 'Lunch — Mughlai',
            category: 'food',
            duration: '1h',
            distance: '3.1 km',
            transport: 'auto',
            cost: 450,
            priority: 'medium',
            notes: 'Try dal makhani and tandoori at a rooftop café.',
            coordinates: null,
            imageSlug: 'agra-taj',
          },
          {
            id: 'itm_1_5',
            time: '14:00',
            endTime: '16:00',
            place: 'Agra Fort',
            category: 'historical',
            duration: '2h',
            distance: '2.5 km',
            transport: 'auto',
            cost: 50,
            priority: 'high',
            notes: 'Look for the Musamman Burj view of the Taj.',
            coordinates: { lat: 27.1795, lng: 78.0211 },
            imageSlug: 'agra-fort',
          },
          {
            id: 'itm_1_6',
            time: '16:45',
            endTime: '18:15',
            place: 'Mehtab Bagh',
            category: 'nature',
            duration: '1h 30m',
            distance: '4.0 km',
            transport: 'auto',
            cost: 30,
            priority: 'medium',
            notes: 'Golden-hour view of the Taj across the Yamuna.',
            coordinates: { lat: 27.1797, lng: 78.04 },
            imageSlug: 'agra-taj',
          },
          {
            id: 'itm_1_7',
            time: '19:30',
            endTime: '20:30',
            place: 'Dinner — petha & chaat',
            category: 'food',
            duration: '1h',
            distance: '1.5 km',
            transport: 'walk',
            cost: 350,
            priority: 'medium',
            notes: 'Wrap up with Agra’s famous petha sweet.',
            coordinates: null,
            imageSlug: 'agra-taj',
          },
        ],
      },
      {
        id: 'day_2',
        day: 2,
        title: 'Fatehpur Sikri & the road home',
        summary: 'A half-day trip to the abandoned Mughal capital, then local markets and the return train.',
        items: [
          {
            id: 'itm_2_1',
            time: '07:00',
            endTime: '08:00',
            place: 'Breakfast at hotel',
            category: 'food',
            duration: '1h',
            distance: '—',
            transport: 'walk',
            cost: 0,
            priority: 'low',
            notes: 'Included with stay.',
            coordinates: null,
            imageSlug: 'hotel',
          },
          {
            id: 'itm_2_2',
            time: '08:00',
            endTime: '12:30',
            place: 'Fatehpur Sikri',
            category: 'historical',
            duration: '4h 30m',
            distance: '39 km',
            transport: 'taxi',
            cost: 900,
            priority: 'high',
            notes: 'Buland Darwaza and Salim Chishti’s tomb.',
            coordinates: { lat: 27.0945, lng: 77.6679 },
            imageSlug: 'agra-fort',
          },
          {
            id: 'itm_2_3',
            time: '13:00',
            endTime: '14:00',
            place: 'Lunch',
            category: 'food',
            duration: '1h',
            distance: '39 km',
            transport: 'taxi',
            cost: 300,
            priority: 'medium',
            notes: 'Simple highway dhaba lunch.',
            coordinates: null,
            imageSlug: 'delhi',
          },
          {
            id: 'itm_2_4',
            time: '15:00',
            endTime: '16:30',
            place: 'Sadar Bazaar & petha shops',
            category: 'shopping',
            duration: '1h 30m',
            distance: '4.5 km',
            transport: 'auto',
            cost: 200,
            priority: 'low',
            notes: 'Pick up marble souvenirs and petha.',
            coordinates: null,
            imageSlug: 'agra-taj',
          },
          {
            id: 'itm_2_5',
            time: '17:30',
            endTime: '19:30',
            place: 'Return train to Delhi',
            category: 'transport',
            duration: '2h',
            distance: '—',
            transport: 'train',
            cost: 590,
            priority: 'high',
            notes: 'AGC → NDLS. Verify timings on IRCTC.',
            coordinates: null,
            imageSlug: 'delhi',
          },
        ],
      },
    ],
    shareToken: null,
    shareEnabled: false,
    aiGenerated: true,
    aiModel: 'demo-planner',
    createdAt: nowIso,
    updatedAt: nowIso,
  };

  const expenses = [
    {
      id: 'exp_demo_1',
      userId: user.id,
      tripId: trip.id,
      amount: 1180,
      category: 'transport',
      description: 'Shatabdi tickets (2 adults)',
      date: '2026-08-22T06:00:00.000Z',
      createdAt: nowIso,
      updatedAt: nowIso,
    },
    {
      id: 'exp_demo_2',
      userId: user.id,
      tripId: trip.id,
      amount: 1800,
      category: 'hotel',
      description: 'The Retreat Agra — 1 night',
      date: '2026-08-22T14:00:00.000Z',
      createdAt: nowIso,
      updatedAt: nowIso,
    },
    {
      id: 'exp_demo_3',
      userId: user.id,
      tripId: trip.id,
      amount: 650,
      category: 'food',
      description: 'Lunch & dinner, day 1',
      date: '2026-08-22T12:30:00.000Z',
      createdAt: nowIso,
      updatedAt: nowIso,
    },
  ];

  const notifications = [
    {
      id: 'ntf_demo_1',
      userId: user.id,
      type: 'trip_reminder',
      title: 'Your Agra trip is coming up',
      body: 'Delhi → Agra starts on 22 Aug. Verify your train timings.',
      read: false,
      data: { tripId: trip.id },
      createdAt: nowIso,
      updatedAt: nowIso,
    },
    {
      id: 'ntf_demo_2',
      userId: user.id,
      type: 'ai_recommendation',
      title: 'AI suggestion ready',
      body: 'Add Mehtab Bagh at sunset — it has the best Taj view.',
      read: true,
      data: { placeId: 'plc_mehtab_bagh' },
      createdAt: nowIso,
      updatedAt: nowIso,
    },
  ];

  return { user, trip, expenses, notifications };
}
