/**
 * Seed transport catalog (demo provider).
 *
 * Schedules and fares are EDITORIAL ESTIMATES for common inter-city routes.
 * Availability is NEVER presented as live — the UI shows "AI estimate" or
 * "Verify availability with provider".
 */

export const trains = [
  {
    id: 'trn_12002',
    name: 'Shatabdi Express',
    number: '12002',
    from: 'New Delhi',
    to: 'Agra',
    departure: '06:00',
    arrival: '07:57',
    durationMin: 117,
    fare: 590,
    classType: 'CC',
    runsOn: 'Daily',
    availability: 'estimate',
  },
  {
    id: 'trn_12050',
    name: 'Gatimaan Express',
    number: '12050',
    from: 'New Delhi',
    to: 'Agra',
    departure: '08:10',
    arrival: '09:50',
    durationMin: 100,
    fare: 750,
    classType: 'CC',
    runsOn: 'Daily',
    availability: 'estimate',
  },
  {
    id: 'trn_12801',
    name: 'Purushottam Express',
    number: '12801',
    from: 'New Delhi',
    to: 'Agra',
    departure: '22:40',
    arrival: '02:25',
    durationMin: 225,
    fare: 340,
    classType: 'SL',
    runsOn: 'Daily',
    availability: 'estimate',
  },
  {
    id: 'trn_12915',
    name: 'Ashram Express',
    number: '12915',
    from: 'New Delhi',
    to: 'Jaipur',
    departure: '15:20',
    arrival: '20:10',
    durationMin: 290,
    fare: 480,
    classType: 'SL',
    runsOn: 'Daily',
    availability: 'estimate',
  },
  {
    id: 'trn_12015',
    name: 'Ajmer Shatabdi',
    number: '12015',
    from: 'New Delhi',
    to: 'Jaipur',
    departure: '06:05',
    arrival: '10:30',
    durationMin: 265,
    fare: 690,
    classType: 'CC',
    runsOn: 'Daily',
    availability: 'estimate',
  },
  {
    id: 'trn_12559',
    name: 'Shiv Ganga Express',
    number: '12559',
    from: 'New Delhi',
    to: 'Varanasi',
    departure: '18:50',
    arrival: '07:15',
    durationMin: 745,
    fare: 640,
    classType: 'SL',
    runsOn: 'Daily',
    availability: 'estimate',
  },
  {
    id: 'trn_12029',
    name: 'Shatabdi Express',
    number: '12029',
    from: 'New Delhi',
    to: 'Amritsar',
    departure: '07:20',
    arrival: '13:30',
    durationMin: 370,
    fare: 830,
    classType: 'CC',
    runsOn: 'Daily',
    availability: 'estimate',
  },
];

export const buses = [
  {
    id: 'bus_001',
    operator: 'UPSRTC Volvo',
    from: 'New Delhi',
    to: 'Agra',
    departure: '07:30',
    arrival: '11:15',
    durationMin: 225,
    fare: 420,
    type: 'AC Sleeper',
    boardingPoint: 'ISBT Kashmere Gate',
    droppingPoint: 'Agra ISBT',
    availability: 'estimate',
  },
  {
    id: 'bus_002',
    operator: 'RSRTC Deluxe',
    from: 'New Delhi',
    to: 'Jaipur',
    departure: '09:00',
    arrival: '14:30',
    durationMin: 330,
    fare: 550,
    type: 'AC Seater',
    boardingPoint: 'Bikaner House',
    droppingPoint: 'Sindhi Camp',
    availability: 'estimate',
  },
  {
    id: 'bus_003',
    operator: 'Private Volvo',
    from: 'New Delhi',
    to: 'Jaipur',
    departure: '22:30',
    arrival: '04:00',
    durationMin: 330,
    fare: 700,
    type: 'AC Sleeper',
    boardingPoint: 'Majnu ka Tila',
    droppingPoint: 'Sindhi Camp',
    availability: 'estimate',
  },
  {
    id: 'bus_004',
    operator: 'UPSRTC Ordinary',
    from: 'New Delhi',
    to: 'Agra',
    departure: '13:00',
    arrival: '17:45',
    durationMin: 285,
    fare: 260,
    type: 'Non-AC Seater',
    boardingPoint: 'ISBT Kashmere Gate',
    droppingPoint: 'Agra ISBT',
    availability: 'estimate',
  },
];

export const localTransport = [
  { id: 'loc_auto', name: 'Auto-rickshaw', icon: 'auto', note: 'Best for short hops', costPerKm: 12 },
  { id: 'loc_taxi', name: 'Cab / Taxi', icon: 'taxi', note: 'Comfortable door-to-door', costPerKm: 18 },
  { id: 'loc_metro', name: 'Metro', icon: 'metro', note: 'Fast in Delhi', costPerKm: 6 },
  { id: 'loc_walk', name: 'Walking', icon: 'walk', note: 'Free & immersive', costPerKm: 0 },
];
