/**
 * Seed hotel catalog (demo provider).
 *
 * Prices are EDITORIAL ESTIMATES, not live availability. The UI always labels
 * these "Estimated" and never presents them as verified real-time data.
 */
export const hotels = [
  {
    id: 'htl_agra_budget_1',
    name: 'Hotel Ganga Ratan',
    city: 'Agra',
    category: 'budget',
    pricePerNight: 900,
    rating: 4.1,
    ratingCount: 1280,
    distanceKm: 2.4,
    amenities: ['Wi-Fi', 'Breakfast', 'AC', 'Parking'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_agra_budget_2',
    name: 'Taj Street Inn',
    city: 'Agra',
    category: 'budget',
    pricePerNight: 1100,
    rating: 4.2,
    ratingCount: 860,
    distanceKm: 1.8,
    amenities: ['Wi-Fi', 'Rooftop', 'AC'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_agra_medium_1',
    name: 'The Retreat Agra',
    city: 'Agra',
    category: 'medium',
    pricePerNight: 2600,
    rating: 4.5,
    ratingCount: 2140,
    distanceKm: 1.2,
    amenities: ['Wi-Fi', 'Breakfast', 'Pool', 'Restaurant', 'Parking'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_agra_premium_1',
    name: 'Tajview Royale',
    city: 'Agra',
    category: 'premium',
    pricePerNight: 7200,
    rating: 4.7,
    ratingCount: 3240,
    distanceKm: 0.9,
    amenities: ['Wi-Fi', 'Breakfast', 'Pool', 'Taj View', 'Spa', 'Restaurant'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_jaipur_budget_1',
    name: 'Pink City Hostel',
    city: 'Jaipur',
    category: 'budget',
    pricePerNight: 750,
    rating: 4.3,
    ratingCount: 1520,
    distanceKm: 3.1,
    amenities: ['Wi-Fi', 'Café', 'Dorm'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_jaipur_medium_1',
    name: 'Hotel Hawa Heights',
    city: 'Jaipur',
    category: 'medium',
    pricePerNight: 2400,
    rating: 4.4,
    ratingCount: 1940,
    distanceKm: 1.5,
    amenities: ['Wi-Fi', 'Breakfast', 'AC', 'Parking', 'Restaurant'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_jaipur_premium_1',
    name: 'Raj Mahal Palace',
    city: 'Jaipur',
    category: 'premium',
    pricePerNight: 9500,
    rating: 4.8,
    ratingCount: 2860,
    distanceKm: 1.1,
    amenities: ['Wi-Fi', 'Breakfast', 'Pool', 'Spa', 'Heritage'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_delhi_budget_1',
    name: 'Backpackers Delhi',
    city: 'New Delhi',
    category: 'budget',
    pricePerNight: 800,
    rating: 4.2,
    ratingCount: 2100,
    distanceKm: 4.0,
    amenities: ['Wi-Fi', 'Café', 'Locker'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_delhi_medium_1',
    name: 'Connaught Residency',
    city: 'New Delhi',
    category: 'medium',
    pricePerNight: 2800,
    rating: 4.4,
    ratingCount: 1720,
    distanceKm: 1.0,
    amenities: ['Wi-Fi', 'Breakfast', 'AC', 'Metro Access'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_delhi_premium_1',
    name: 'The Imperial Residency',
    city: 'New Delhi',
    category: 'premium',
    pricePerNight: 11000,
    rating: 4.8,
    ratingCount: 3980,
    distanceKm: 1.4,
    amenities: ['Wi-Fi', 'Breakfast', 'Pool', 'Spa', 'Concierge', 'Gym'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_varanasi_medium_1',
    name: 'Ganga View Haveli',
    city: 'Varanasi',
    category: 'medium',
    pricePerNight: 2600,
    rating: 4.5,
    ratingCount: 1830,
    distanceKm: 0.6,
    amenities: ['Wi-Fi', 'Breakfast', 'Ghat View'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
  {
    id: 'htl_amritsar_medium_1',
    name: 'Golden Temple Stay',
    city: 'Amritsar',
    category: 'medium',
    pricePerNight: 2300,
    rating: 4.5,
    ratingCount: 1410,
    distanceKm: 0.8,
    amenities: ['Wi-Fi', 'Breakfast', 'AC'],
    imageSlug: 'hotel',
    dataTrust: 'estimate',
  },
];

export const hotelsById = new Map(hotels.map((h) => [h.id, h]));
